// ادغام لیبل‌ها
const LABELS = {
    "G-LIN": "هوش زبانی",
    "G-LOG": "هوش ریاضی",
    "G-SPA": "هوش فضایی",
    "G-BOD": "هوش بدنی-حرکتی",
    "G-MUS": "هوش موسیقایی",
    "G-INTER": "هوش میان‌فردی",
    "G-INTRA": "هوش درون‌فردی",
    "R-CRE": "نقش خلاق",
    "R-EXE": "نقش اجرایی",
    "R-SUP": "نقش پشتیبان",
    "R-INTRA": "نقش خودرهبری",
    "TR": "ترسیمی",
    "TS": "تصویری",
    "PO": "پشتیبانی_مالی",
    "RO": "روابط عمومی",
    "NA": "نمایشی",
    "FA": "فرهنگی",
    "ROLE_R-EXE": "نقش اجرایی",
    "ROLE_R-SUP": "نقش پشتیبان",
    "ROLE_R-CRE": "نقش خلاق",
    "ROLE_R-INTRA": "نقش خودرهبری"
};

// ==========================================
// ماتریس وزن‌دهی حوزه‌های حرفه‌ای/هنری (علاقه و خودکارآمدی)
// جایگزین questionWeights و categoryMatrix
// ==========================================
const domainWeights = {
    "TR-1": { INT_TR: 0.9 },
    "G-LIN-1": { SE_RO: 0.6, SE_FA: 0.7, SE_NA: 0.3 },
    "RO-1": { INT_RO: 1.0 },
    "R-CRE-1": { INT_TR: 0.5, INT_TS: 0.3, INT_FA: 0.4, INT_NA: 0.3 },
    "TS-1": { INT_TS: 1.0 },
    "G-LOG-1": { SE_PO: 0.7 },
    "NA-1": { INT_NA: 1.0, SE_NA: 0.7 },
    "R-EXE-1": { SE_PO: 0.8 },
    "PO-1": { INT_PO: 1.0 },
    "G-SPA-1": { SE_TR: 0.8, SE_TS: 0.6 },
    "Q-REV-1": {},
    "FA-1": { INT_FA: 1.0 },
    "R-SUP-1": { SE_PO: 0.6 },
    "G-MUS-1": { SE_NA: 0.8 },
    "G-INTER-1": { SE_RO: 0.8, SE_NA: 0.4 },
    "G-BOD-1": { SE_TR: 0.5, SE_NA: 0.4 },
    "R-INTRA-1": {},
    "TR-2": { INT_TR: 0.8, SE_TR: 0.6 },
    "G-LIN-2": { INT_FA: 0.8, SE_NA: 0.4 },
    "R-CRE-2": { INT_TR: 0.4, INT_TS: 0.3, INT_FA: 0.4, INT_NA: 0.3 },
    "Q-ATT-1": {},
    "TS-2": { INT_TS: 0.7, SE_TS: 0.9 },
    "G-LOG-2": { INT_PO: 0.8 },
    "RO-2": { INT_RO: 1.0 },
    "NA-2": { INT_NA: 0.9, SE_NA: 0.7 },
    "R-EXE-2": { INT_PO: 0.5, SE_PO: 0.6 },
    "PO-2": { SE_PO: 0.9 },
    "G-SPA-2": { SE_TR: 0.7, SE_TS: 0.5 },
    "FA-2": { INT_FA: 1.0 },
    "R-SUP-2": { SE_RO: 0.4, SE_PO: 0.7 },
    "Q-DUP-2": {},
    "G-MUS-2": { SE_NA: 0.8 },
    "G-INTER-2": { SE_RO: 0.9, SE_NA: 0.5 },
    "G-BOD-2": { SE_NA: 0.8 },
    "R-INTRA-2": {},
    "TR-3": { SE_TR: 1.0 },
    "G-LIN-3": { SE_RO: 0.7, SE_FA: 0.6, SE_NA: 0.4 },
    "RO-3": { INT_RO: 0.9 },
    "R-CRE-3": { INT_TR: 0.3, INT_TS: 0.2, INT_FA: 0.3, INT_NA: 0.2 },
    "TS-3": { INT_TS: 0.5, SE_TS: 1.0 },
    "G-LOG-3": { INT_PO: 0.8 },
    "NA-3": { INT_NA: 0.8, SE_NA: 0.6 },
    "R-EXE-3": { SE_PO: 0.9 },
    "Q-REV-2": {},
    "R-SUP-3": { SE_RO: 0.5, SE_PO: 0.6 },
    "G-SPA-3": { SE_TR: 0.6, SE_TS: 0.4 },
    "FA-3": { INT_FA: 0.9, SE_FA: 0.8, SE_NA: 0.3 },
    "PO-3": { INT_PO: 0.9 },
    "G-MUS-3": { SE_NA: 0.7 },
    "G-INTER-3": { INT_RO: 0.8, SE_RO: 0.7, SE_NA: 0.5 },
    "G-BOD-3": {},
    "R-INTRA-3": {},
    "FA-4": { SE_FA: 1.0 },
    "Q-ATT-2": {},
    "TR-4": { INT_TR: 0.9, SE_TR: 0.7 },
    "RO-4": { INT_RO: 0.8, SE_RO: 0.9 },
    "R-CRE-4": { SE_TR: 0.3, SE_TS: 0.2, SE_FA: 0.3, SE_NA: 0.2 },
    "Q-DUP-1": {},
    "G-LOG-4": { SE_PO: 0.8 },
    "NA-4": { INT_NA: 1.0 },
    "G-SPA-4": { SE_TR: 0.7, SE_TS: 0.5 },
    "R-EXE-4": { SE_PO: 0.9 },
    "PO-4": { SE_PO: 0.9 },
    "TS-4": { INT_TS: 0.8, SE_TS: 0.7 },
    "G-LIN-4": { INT_FA: 0.9 },
    "PO-5": { SE_PO: 0.9 },
    "G-MUS-4": { SE_NA: 0.6 },
    "NA-5": { INT_NA: 0.9 },
    "G-BOD-4": {},
    "TR-5": { INT_TR: 1.0 },
    "G-LIN-5": { SE_RO: 0.8, SE_FA: 0.7, SE_NA: 0.3 },
    "RO-5": { INT_RO: 0.9 },
    "Q-REV-3": {},
    "TS-5": { INT_TS: 0.3, SE_TS: 1.0 },
    "G-MUS-5": { INT_NA: 0.7 },
    "PO-6": { SE_PO: 1.0 },
    "G-SPA-5": { SE_TR: 0.6, SE_TS: 0.8 },
    "FA-5": { INT_FA: 0.8 },
    "G-BOD-5": { SE_NA: 0.7 },
    "TR-6": { INT_TR: 0.9 },
    "RO-6": { SE_RO: 1.0 },
    "TS-6": { INT_TS: 0.9 },
    "NA-6": { INT_NA: 1.0 },
    "R-SUP-4": { INT_PO: 0.5, SE_PO: 0.3 },
    "FA-6": { INT_FA: 1.0 },
    "Q-DUP-3": {},
    "G-LOG-5": { SE_PO: 0.9 },
    "G-INTER-4": { SE_RO: 0.8, SE_NA: 0.6 },
    "G-INTER-5": { SE_RO: 0.9, SE_NA: 0.5 },
    "R-INTRA-4": { SE_PO: 0.5 }
};

// وزن‌های نقش‌های چهارگانه
const roleWeights = {
    "TR-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.3, "R-INTRA": 0},
    "G-LIN-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-CRE-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 1.0, "R-INTRA": 0},
    "TS-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LOG-1": {"R-EXE": 0.2, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-EXE-1": {"R-EXE": 1.0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "PO-1": {"R-EXE": 0.5, "R-SUP": 0.2, "R-CRE": 0, "R-INTRA": 0},
    "G-SPA-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "Q-REV-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "FA-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0.3},
    "R-SUP-1": {"R-EXE": 0, "R-SUP": 1.0, "R-CRE": 0, "R-INTRA": 0},
    "G-MUS-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-INTER-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-BOD-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-INTRA-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 1.0},
    "TR-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LIN-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-CRE-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 1.0, "R-INTRA": 0},
    "Q-ATT-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "TS-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LOG-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-EXE-2": {"R-EXE": 1.0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "PO-2": {"R-EXE": 0.3, "R-SUP": 0.3, "R-CRE": 0, "R-INTRA": 0},
    "G-SPA-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "FA-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-SUP-2": {"R-EXE": 0, "R-SUP": 1.0, "R-CRE": 0, "R-INTRA": 0},
    "Q-DUP-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-MUS-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-INTER-2": {"R-EXE": 0, "R-SUP": 0.3, "R-CRE": 0, "R-INTRA": 0},
    "G-BOD-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-INTRA-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 1.0},
    "TR-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.2, "R-INTRA": 0},
    "G-LIN-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.2, "R-INTRA": 0},
    "R-CRE-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 1.0, "R-INTRA": 0},
    "TS-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LOG-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-EXE-3": {"R-EXE": 1.0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "Q-REV-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-SUP-3": {"R-EXE": 0, "R-SUP": 1.0, "R-CRE": 0, "R-INTRA": 0},
    "G-SPA-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "FA-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.3, "R-INTRA": 0},
    "PO-3": {"R-EXE": 0.4, "R-SUP": 0.3, "R-CRE": 0, "R-INTRA": 0},
    "G-MUS-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-INTER-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-BOD-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-INTRA-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 1.0},
    "FA-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.2, "R-INTRA": 0},
    "Q-ATT-2": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "TR-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-CRE-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 1.0, "R-INTRA": 0},
    "Q-DUP-1": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LOG-4": {"R-EXE": 0.3, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-SPA-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-EXE-4": {"R-EXE": 1.0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "PO-4": {"R-EXE": 0.4, "R-SUP": 0.2, "R-CRE": 0, "R-INTRA": 0},
    "TS-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.3, "R-INTRA": 0},
    "G-LIN-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "PO-5": {"R-EXE": 0.3, "R-SUP": 0.4, "R-CRE": 0, "R-INTRA": 0},
    "G-MUS-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-BOD-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "TR-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.3, "R-INTRA": 0},
    "G-LIN-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.3, "R-INTRA": 0},
    "Q-REV-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "TS-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-MUS-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0.2, "R-INTRA": 0},
    "PO-6": {"R-EXE": 0.3, "R-SUP": 0.4, "R-CRE": 0, "R-INTRA": 0},
    "G-SPA-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "FA-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-BOD-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "TR-6": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "RO-6": {"R-EXE": 0, "R-SUP": 0.2, "R-CRE": 0, "R-INTRA": 0},
    "TS-6": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "NA-6": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-SUP-4": {"R-EXE": 0, "R-SUP": 1.0, "R-CRE": 0, "R-INTRA": 0},
    "FA-6": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0.3},
    "Q-DUP-3": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-LOG-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "G-INTER-4": {"R-EXE": 0, "R-SUP": 0.3, "R-CRE": 0, "R-INTRA": 0},
    "G-INTER-5": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 0},
    "R-INTRA-4": {"R-EXE": 0, "R-SUP": 0, "R-CRE": 0, "R-INTRA": 1.0}
};

const maxWeights = {
    "R-EXE": 6.7,
    "R-SUP": 6.6,
    "R-CRE": 6.3,
    "R-INTRA": 4.6
};

// ==========================================
// ماتریس وزن‌دهی هوش‌های چندگانه (MI)
// ==========================================
const MI_MAX_WEIGHTS = {
    LIN: 12.1, LOG: 8.1, SPA: 13.9, MUS: 5.4, BOD: 6.8, INTER: 12.1, INTRA: 5.4
};

const MI_LABELS = {
    LIN: 'زبانی', LOG: 'منطقی-ریاضی', SPA: 'فضایی', 
    MUS: 'موسیقایی', BOD: 'بدنی-حرکتی', INTER: 'میان‌فردی', INTRA: 'درون‌فردی'
};

const MI_WEIGHTS = {
    "TR-1": {LIN: 0, LOG: 0, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LIN-1": {LIN: 1.0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.7, INTRA: 0},
    "R-CRE-1": {LIN: 0.3, LOG: 0, SPA: 0.3, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TS-1": {LIN: 0, LOG: 0, SPA: 0.6, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LOG-1": {LIN: 0, LOG: 1.0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "NA-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0.2, INTER: 0.4, INTRA: 0},
    "R-EXE-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-1": {LIN: 0, LOG: 0.3, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-SPA-1": {LIN: 0, LOG: 0, SPA: 1.0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "Q-REV-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "FA-1": {LIN: 0.7, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0.3},
    "R-SUP-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.2, INTRA: 0.2},
    "G-MUS-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 1.0, BOD: 0, INTER: 0, INTRA: 0},
    "G-INTER-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 1.0, INTRA: 0},
    "G-BOD-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 1.0, INTER: 0, INTRA: 0},
    "R-INTRA-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 1.0},
    "TR-2": {LIN: 0, LOG: 0, SPA: 0.8, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LIN-2": {LIN: 1.0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "R-CRE-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "Q-ATT-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TS-2": {LIN: 0, LOG: 0, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LOG-2": {LIN: 0, LOG: 1.0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-2": {LIN: 0.3, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.5, INTRA: 0},
    "NA-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0.4, INTER: 0.4, INTRA: 0},
    "R-EXE-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-2": {LIN: 0, LOG: 0.4, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-SPA-2": {LIN: 0, LOG: 0, SPA: 1.0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "FA-2": {LIN: 0.7, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "R-SUP-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.5, INTRA: 0.2},
    "Q-DUP-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-MUS-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 1.0, BOD: 0, INTER: 0, INTRA: 0},
    "G-INTER-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 1.0, INTRA: 0},
    "G-BOD-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 1.0, INTER: 0, INTRA: 0},
    "R-INTRA-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 1.0},
    "TR-3": {LIN: 0, LOG: 0, SPA: 0.8, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LIN-3": {LIN: 1.0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.4, INTRA: 0},
    "R-CRE-3": {LIN: 0, LOG: 0.3, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TS-3": {LIN: 0, LOG: 0.2, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LOG-3": {LIN: 0, LOG: 1.0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "NA-3": {LIN: 0.3, LOG: 0, SPA: 0, MUS: 0.2, BOD: 0.4, INTER: 0, INTRA: 0},
    "R-EXE-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "Q-REV-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "R-SUP-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.5, INTRA: 0.2},
    "G-SPA-3": {LIN: 0, LOG: 0, SPA: 1.0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "FA-3": {LIN: 0.8, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-3": {LIN: 0, LOG: 0.2, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-MUS-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 1.0, BOD: 0, INTER: 0, INTRA: 0},
    "G-INTER-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 1.0, INTRA: 0},
    "G-BOD-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 1.0, INTER: 0, INTRA: 0},
    "R-INTRA-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 1.0},
    "FA-4": {LIN: 0.8, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "Q-ATT-2": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TR-4": {LIN: 0, LOG: 0, SPA: 0.8, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.7, INTRA: 0},
    "R-CRE-4": {LIN: 0, LOG: 0.3, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "Q-DUP-1": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LOG-4": {LIN: 0, LOG: 1.0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "NA-4": {LIN: 0.3, LOG: 0, SPA: 0, MUS: 0.2, BOD: 0.5, INTER: 0.3, INTRA: 0},
    "G-SPA-4": {LIN: 0, LOG: 0, SPA: 1.0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "R-EXE-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-4": {LIN: 0, LOG: 0.4, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TS-4": {LIN: 0.3, LOG: 0, SPA: 0.6, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LIN-4": {LIN: 1.0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-5": {LIN: 0, LOG: 0.3, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-MUS-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 1.0, BOD: 0, INTER: 0.2, INTRA: 0},
    "NA-5": {LIN: 0.3, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.4, INTRA: 0},
    "G-BOD-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 1.0, INTER: 0, INTRA: 0},
    "TR-5": {LIN: 0, LOG: 0, SPA: 0.8, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LIN-5": {LIN: 1.0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-5": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.6, INTRA: 0},
    "Q-REV-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "TS-5": {LIN: 0, LOG: 0, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-MUS-5": {LIN: 0, LOG: 0, SPA: 0, MUS: 1.0, BOD: 0, INTER: 0, INTRA: 0},
    "PO-6": {LIN: 0, LOG: 0.4, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-SPA-5": {LIN: 0, LOG: 0.3, SPA: 1.0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "FA-5": {LIN: 0.7, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-BOD-5": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 1.0, INTER: 0, INTRA: 0},
    "TR-6": {LIN: 0, LOG: 0, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "RO-6": {LIN: 0.5, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.6, INTRA: 0},
    "TS-6": {LIN: 0, LOG: 0, SPA: 0.7, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "NA-6": {LIN: 0.4, LOG: 0, SPA: 0, MUS: 0, BOD: 0.3, INTER: 0.4, INTRA: 0},
    "R-SUP-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0.3, INTRA: 0.2},
    "FA-6": {LIN: 0.7, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0.3},
    "Q-DUP-3": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-LOG-5": {LIN: 0, LOG: 1.0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 0},
    "G-INTER-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 1.0, INTRA: 0},
    "G-INTER-5": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 1.0, INTRA: 0},
    "R-INTRA-4": {LIN: 0, LOG: 0, SPA: 0, MUS: 0, BOD: 0, INTER: 0, INTRA: 1.0}
};

// data_config.js

const combinedConfig = {
    weightsA: {
        TR: { LIN:0, LOG:1, SPA:3, MUS:0, BOD:1.25, INTER:0.5, INTRA:0, 'R-CRE':2.5, 'R-EXE':1.25, 'R-SUP':0, 'R-INTRA':1.75 },
        TS: { LIN:0, LOG:1.25, SPA:2.5, MUS:1, BOD:1, INTER:0, INTRA:1, 'R-CRE':2, 'R-EXE':2, 'R-SUP':0, 'R-INTRA':1.5 },
        RO: { LIN:2, LOG:1, SPA:0, MUS:0, BOD:1, INTER:0, INTRA:2, 'R-CRE':1.5, 'R-EXE':2, 'R-SUP':1.5, 'R-INTRA':0.5 },
        FA: { LIN:3, LOG:1, SPA:1, MUS:0, BOD:0, INTER:1.1, INTRA:0.5, 'R-CRE':3, 'R-EXE':0.5, 'R-SUP':0, 'R-INTRA':2 },
        NA: { LIN:2, LOG:1, SPA:1, MUS:2, BOD:2, INTER:0.5, INTRA:0.5, 'R-CRE':2.25, 'R-EXE':1, 'R-SUP':0, 'R-INTRA':2 },
        PO: { LIN:1, LOG:2, SPA:0, MUS:0, BOD:0, INTER:1, INTRA:2, 'R-CRE':0, 'R-EXE':2.5, 'R-SUP':3, 'R-INTRA':0 }
    },
    itemsB: {
        'TR-1': { domain: 'TR', weight: 1.0 }, 'TR-2': { domain: 'TR', weight: 1.0 }, 'TR-3': { domain: 'TR', weight: 1.2 },
        'TR-4': { domain: 'TR', weight: 1.0 }, 'TR-5': { domain: 'TR', weight: 1.2 }, 'TR-6': { domain: 'TR', weight: 0.8 },
        'TS-1': { domain: 'TS', weight: 0.9 }, 'TS-2': { domain: 'TS', weight: 1.2 }, 'TS-3': { domain: 'TS', weight: 1.1 },
        'TS-4': { domain: 'TS', weight: 1.2 }, 'TS-5': { domain: 'TS', weight: 1.2 }, 'TS-6': { domain: 'TS', weight: 0.9 },
        'RO-1': { domain: 'RO', weight: 1.0 }, 'RO-2': { domain: 'RO', weight: 0.9 }, 'RO-3': { domain: 'RO', weight: 1.1 },
        'RO-4': { domain: 'RO', weight: 1.0 }, 'RO-5': { domain: 'RO', weight: 1.0 }, 'RO-6': { domain: 'RO', weight: 1.3 },
        'FA-1': { domain: 'FA', weight: 0.9 }, 'FA-2': { domain: 'FA', weight: 0.8 }, 'FA-3': { domain: 'FA', weight: 1.3 },
        'FA-4': { domain: 'FA', weight: 1.2 }, 'FA-5': { domain: 'FA', weight: 0.9 }, 'FA-6': { domain: 'FA', weight: 0.9 },
        'NA-1': { domain: 'NA', weight: 1.0 }, 'NA-2': { domain: 'NA', weight: 0.9 }, 'NA-3': { domain: 'NA', weight: 1.1 },
        'NA-4': { domain: 'NA', weight: 1.2 }, 'NA-5': { domain: 'NA', weight: 1.0 }, 'NA-6': { domain: 'NA', weight: 1.3 },
        'PO-1': { domain: 'PO', weight: 1.0 }, 'PO-2': { domain: 'PO', weight: 1.0 }, 'PO-3': { domain: 'PO', weight: 0.9 },
        'PO-4': { domain: 'PO', weight: 1.2 }, 'PO-5': { domain: 'PO', weight: 1.1 }, 'PO-6': { domain: 'PO', weight: 1.2 }
    }
};

const TEXT_TEMPLATES = {
    gapPositive: [
        "پتانسیل خاموش: توانمندی شما بالاست اما نیازمند خودباوری بیشتری هستید.",
        "استعداد پنهان: مهارت ذاتی خوبی دارید اما باید به توانایی‌هایتان بیشتر ایمان بیاورید.",
        "فرصت رشد درونی: ظرفیت‌های شما از آنچه خودتان فکر می‌کنید بیشتر است؛ با کمی جسارت می‌درخشید."
    ],
    gapNegative: [
        "نیاز به مهارت‌افزایی: اعتماد به نفس شما عالی است، اما برای رسیدن به سطح ایده‌آل باید بیشتر تمرین کنید.",
        "اعتماد کاذب: باور شما از مهارت فعلی‌تان کمی جلوتر است؛ پیشنهاد می‌شود دانش فنی خود را افزایش دهید.",
        "خوش‌بینی مفرط: برای اینکه عملکردتان با باورتان همگام شود، به آموزش‌های عملی و واقع‌بینانه نیاز دارید."
    ],
    gapNeutral: [
        "نگاه واقع‌بینانه: شناخت شما از توانمندی‌هایتان در این حوزه بسیار دقیق و منطبق بر واقعیت است.",
        "خودآگاهی مطلوب: تعادل بسیار خوبی بین سطح مهارت واقعی و خودباوری شما وجود دارد.",
        "ارزیابی دقیق: درک درستی از جایگاه خود دارید و انتظاراتتان کاملاً متناسب با توانایی‌هایتان است."
    ],
    quadGold: [
        "نقطه طلایی! هم علاقه و اشتیاق دارید و هم توانایی ذاتی. این حوزه می‌تواند مسیر اصلی موفقیت شما باشد.",
        "بالاترین پتانسیل! ترکیب عالیِ انگیزه و استعداد. سرمایه‌گذاری در این بخش قطعا سودآور خواهد بود."
    ],
    quadUnmotivated: [
        "استعداد بی‌انگیزه! با وجود توانایی بالا، علاقه چندانی نشان نمی‌دهید. ممکن است این مهارت هدر برود.",
        "پتانسیل رها شده! توانایی انجام این کار را دارید، اما چون موتور محرکِ علاقه خاموش است، پیشرفت سخت می‌شود."
    ],
    quadInterested: [
        "علاقه‌مندِ نیازمند پرورش! انگیزه بالای شما ارزشمند است، اما باید روی تقویت مهارت‌های پایه وقت بگذارید.",
        "اشتیاق بالا، مهارت متوسط! با توجه به علاقه‌ای که دارید، اگر روی آموزش تمرکز کنید، به سرعت رشد خواهید کرد."
    ],
    quadNone: [
        "خارج از اولویت! نه علاقه کافی وجود دارد و نه استعداد بارزی. بهتر است انرژی خود را جای دیگری صرف کنید.",
        "توصیه نمی‌شود! به دلیل ضعف همزمان در انگیزه و مهارت ذاتی، این حوزه پیشنهاد نمی‌گردد."
    ]
};
